import { reactive } from 'vue'
const menus = reactive<menuListType[]>([
  {
    component: "Layout",
    path: "dashboard",
    menuType: "M",
    id: 1,
    pId: 0,
    title: "Dashboard",
    icon: "appstore-outlined",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "dashboard/workbench/index",
    path: "/dashboard/workbench",
    menuType: "C",
    id: 101,
    pId: 1,
    title: "工作台",
    icon: "",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "Layout",
    path: "system",
    menuType: "M",
    id: 2,
    pId: 0,
    title: "系统管理",
    icon: "setting-outlined",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "system/menu/index",
    path: "/system/menu",
    menuType: "C",
    id: 201,
    pId: 2,
    title: "菜单管理",
    icon: "",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "",
    path: "",
    menuType: "F",
    id: 20101,
    pId: 201,
    title: "新增",
    icon: "",
    perms: "add",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "",
    path: "",
    menuType: "F",
    id: 20102,
    pId: 201,
    title: "编辑",
    icon: "",
    perms: "update",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "",
    path: "",
    menuType: "F",
    id: 20103,
    pId: 201,
    title: "删除",
    icon: "",
    perms: "delete",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "system/role/index",
    path: "/system/role",
    menuType: "C",
    id: 202,
    pId: 2,
    title: "角色管理",
    icon: "",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "",
    path: "",
    menuType: "F",
    id: 20201,
    pId: 202,
    title: "新增",
    icon: "",
    perms: "add",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "",
    path: "",
    menuType: "F",
    id: 20202,
    pId: 202,
    title: "编辑",
    icon: "",
    perms: "update",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "",
    path: "",
    menuType: "F",
    id: 20203,
    pId: 202,
    title: "删除",
    icon: "",
    perms: "delete",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "system/user/index",
    path: "/system/user",
    menuType: "C",
    id: 203,
    pId: 2,
    title: "用户管理",
    icon: "",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "",
    path: "",
    menuType: "F",
    id: 20301,
    pId: 203,
    title: "新增",
    icon: "",
    perms: "add",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "",
    path: "",
    menuType: "F",
    id: 20302,
    pId: 203,
    title: "编辑",
    icon: "",
    perms: "update",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "",
    path: "",
    menuType: "F",
    id: 20303,
    pId: 203,
    title: "删除",
    icon: "",
    perms: "delete",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "Layout",
    path: "menu",
    menuType: "M",
    id: 3,
    pId: 0,
    title: "菜单嵌套",
    icon: "appstore-outlined",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "menu/menu1/index",
    path: "/menu/menu1",
    menuType: "C",
    id: 301,
    pId: 3,
    title: "菜单1",
    icon: "",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "Layout",
    path: "menu2",
    menuType: "M",
    id: 302,
    pId: 3,
    title: "菜单2",
    icon: "appstore-outlined",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "menu/menu2/menu21/index",
    path: "/menu/menu2/menu21",
    menuType: "C",
    id: 30201,
    pId: 302,
    title: "菜单2-1",
    icon: "appstore-outlined",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 0,
    hidden: 1,
  },
  {
    component: "Layout",
    path: "menu3",
    menuType: "M",
    id: 303,
    pId: 3,
    title: "菜单3",
    icon: "appstore-outlined",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "menu/menu3/menu31/index",
    path: "/menu/menu3/menu31",
    menuType: "C",
    id: 30301,
    pId: 303,
    title: "菜单3-1",
    icon: "",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "Layout",
    path: "menu312",
    menuType: "M",
    id: 30302,
    pId: 303,
    title: "菜单3-2",
    icon: "appstore-outlined",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "menu/menu3/menu31/menu312/index",
    path: "/menu/menu3/menu31/menu312",
    menuType: "C",
    id: 3030201,
    pId: 30302,
    title: "菜单3-2-1",
    icon: "",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "Layout",
    path: "table",
    menuType: "M",
    id: 4,
    pId: 0,
    title: "Table表格",
    icon: "bar-chart-outlined",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "table/useTable/index",
    path: "/table/useTable",
    menuType: "C",
    id: 401,
    pId: 4,
    title: "Hooks Table",
    icon: "bar-chart-outlined",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "",
    path: "",
    menuType: "F",
    id: 40101,
    pId: 401,
    title: "新增",
    icon: "",
    perms: "add",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "",
    path: "",
    menuType: "F",
    id: 40102,
    pId: 401,
    title: "编辑",
    icon: "",
    perms: "update",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "",
    path: "",
    menuType: "F",
    id: 40103,
    pId: 401,
    title: "删除",
    icon: "",
    perms: "delete",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "table/useComponent/index",
    path: "/table/useComponent",
    menuType: "C",
    id: 402,
    pId: 4,
    title: "Component Table",
    icon: "bar-chart-outlined",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "",
    path: "",
    menuType: "F",
    id: 40201,
    pId: 402,
    title: "新增",
    icon: "",
    perms: "add",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "",
    path: "",
    menuType: "F",
    id: 40202,
    pId: 402,
    title: "编辑",
    icon: "",
    perms: "update",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "",
    path: "",
    menuType: "F",
    id: 40203,
    pId: 402,
    title: "删除",
    icon: "",
    perms: "delete",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "",
    path: "",
    menuType: "F",
    id: 40204,
    pId: 402,
    title: "导出",
    icon: "",
    perms: "export",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "Layout",
    path: "commonly",
    menuType: "M",
    id: 5,
    pId: 0,
    title: "常用组件",
    icon: "appstore-outlined",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "commonly/editor/index",
    path: "/commonly/editor",
    menuType: "C",
    id: 501,
    pId: 5,
    title: "富文本编辑器",
    icon: "",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "commonly/selectIcon/index",
    path: "/commonly/selectIcon",
    menuType: "C",
    id: 502,
    pId: 5,
    title: "Icon选择器",
    icon: "",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "commonly/svgIcon/index",
    path: "/commonly/svgIcon",
    menuType: "C",
    id: 505,
    pId: 5,
    title: "SVG图标",
    icon: "",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "commonly/upload/index",
    path: "/commonly/upload",
    menuType: "C",
    id: 503,
    pId: 5,
    title: "上传组件",
    icon: "",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "commonly/batchImport/index",
    path: "/commonly/batchImport",
    menuType: "C",
    id: 504,
    pId: 5,
    title: "导入数据",
    icon: "",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "Layout",
    path: "feat",
    menuType: "M",
    id: 6,
    pId: 0,
    title: "更多功能",
    icon: "funnel-plot-outlined",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "feat/directive/index",
    path: "/feat/directive",
    menuType: "C",
    id: 601,
    pId: 6,
    title: "自定义指令",
    icon: "",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "feat/infoPage/index",
    path: "/feat/infoPage",
    menuType: "C",
    id: 602,
    pId: 6,
    title: "跳转详情页",
    icon: "",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "feat/loginExpired/index",
    path: "/feat/loginExpired",
    menuType: "C",
    id: 603,
    pId: 6,
    title: "登录过期",
    icon: "",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 1,
    hidden: 1,
  },
  {
    component: "Layout",
    path: "link",
    menuType: "M",
    id: 7,
    pId: 0,
    title: "外链示例",
    icon: "desktop-outlined",
    perms: "",
    isFrame: 0,
    status: 1,
    keepAlive: 0,
    hidden: 1,
  },
  {
    component: "",
    path: "http://121.4.119.52:81",
    menuType: "C",
    id: 701,
    pId: 7,
    title: "练习官网demo",
    icon: "desktop-outlined",
    perms: "",
    isFrame: 1,
    status: 1,
    keepAlive: 0,
    hidden: 1,
  },
  {
    component: "",
    path: "https://github.com/1421788142/WAdmin",
    menuType: "C",
    id: 702,
    pId: 7,
    title: "github地址",
    icon: "github-outlined",
    perms: "",
    isFrame: 1,
    status: 1,
    keepAlive: 0,
    hidden: 1,
  },
  {
    component: "",
    path: "http://121.4.119.52:82",
    menuType: "C",
    id: 703,
    pId: 7,
    title: "WAdmin文档",
    icon: "file-text-outlined",
    perms: "",
    isFrame: 1,
    status: 1,
    keepAlive: 0,
    hidden: 1,
  },
])

export default menus